### ISSUE TITLE
 [ copy selection as html ] a quickscript to copy the selected text as HTML with rainbow parens 

### ISSUE THREAD

**Issue by soapdog** [Quickscript-Competiton/July2020entries#14]
Please enter the competition here:

## code
https://gist.github.com/soapdog/74b0903b2e96aea1e60425154fd2b97e

## Licence 
MIT

## contact details 
Andre Garzia on Racket Slack

**Comment by Metaxal** [comment]
Awesome!

One thing you could add to your script is the option to save the html to a file and open the file in the default browser.
You can use `message-box` to ask a yes/no question, then [browser/external](https://docs.racket-lang.org/browser/index.html) (or even [browser](https://docs.racket-lang.org/browser/index.html) if you feel a little adventurous) to display the page.

Just one boring but important thing (but IANAL): The code by Erkin does not have a license, which means that by default you're not allowed to reuse it (and furthermore relicense it). See https://choosealicense.com/no-permission/
The best option is to ask Erkin to license the original code in MIT/Apache2 for example, so you can freely use it with one of these licenses.
Otherwise you may need Erkin to grant your this authorization directly, and you need to be able to provide proof if requested. (So first option is still best.)

**Comment by soapdog** [comment]
@Metaxal,

Ahead of you in this one. I have asked Erkin for permission before I considered sending in the script:

https://toot.cafe/web/statuses/104564804853222297

Is that public exchange of messages good enough to be considered "proof"? As you can see from the timestamps, we chatted about it yesterday and I've submit the script just today.

**Comment by soapdog** [comment]
Also, I might update the gist with a better gui like the one I did for the other script so that you can select CSS, open browser, etc.

**Comment by Metaxal** [comment]
Excellent! Maybe keep a screenshot :) That should be enough for such a small snippet in any case, as long as Erkin is fine with it. (but again, I'm no lawyer)

**Comment by erkin** [comment]
My mistake for neglecting to add a licence to the page. I figured it's too brief to justify one. :sweat_smile: 
I put a CC0 mark on the webpage just to make sure.

**Comment by spdegabrielle** [comment]
Thank you @erkin for creating https://erkin.party/syntax/ and Andre @soapdog for making the quickscript - I’ll definitely be using this myself !
