### ISSUE TITLE
Fishy completion: autocompletion that is guaranteed to be in scope.

### ISSUE THREAD

**Issue by sorawee** [Quickscript-Competiton/July2020entries#17]
Please enter the competition here:

## code
https://github.com/sorawee/fishy-completion

## Licence 
Apache 2/MIT

## contact details 
@sorawee on Slack/GitHub

**Comment by Metaxal** [comment]
Oh yeah, very cool!

Here's a small failure case:
```racket
#lang racket

(define visit-url #f)
(define visit-file #f)
(define visigo #t)

(λ ()
  visi@
  (visit-file))
```
where the `@` is the cursor's place and is not part of the text. Then calling fishy-completion once yields:
```racket
#lang racket

(define visit-url #f)
(define visit-file #f)
(define visigo #t)

(λ ()
  visi@igo  (visit-file))

```

**Comment by sorawee** [comment]
Fixed. Thanks for the report!

**Comment by Metaxal** [comment]
Awesome, it works now! (I had forgotten to unload the persistent script... I need to detect if the file has changed and do it automatically at least in these cases)

The only issue now is that the keybinding doesn't work for me on unix. It's not used by anything else apparently, so I'm not sure what's going on.
It's not the first time I observe that keybindings don't work as expected, but I don't know what to do about that :-/

**Comment by sorawee** [comment]
Is there a value of having "Unload persistent scripts" separately from "Compile scripts and reload"? I always need to execute both of them together. 

Also, can we get a keybinding for these two commands (or one command if you are to combine them)?

I will investigate what's going on with the unix keybinding when I have free time.

**Comment by Metaxal** [comment]
Yeah, I could certainly also do unload persistent scripts with recompile and reload, that makes sense. I think I should also check the timestamps and changes in properties in any case.

You can already access all the items in the Manage scripts submenu with the keyboard (that's how I use it myself). The keybinding is `alt-s;m;c`:
alt-S: opens the script menu
M: opens the "&Manage Scripts" submenu
C: selects the "&Compile and reload" item

I think that's good enough and for now I don't intend to add keybindings to these items because so many are already defined (and don't work properly).

Regarding keybindings, I could also (on top of menu-keybindings) extend the keymap, so as to be able to use more complex keybindings. (I just tested, and as long as a menu doesn't define "alt-x" for example, you can use a sequence like "alt-x;v".)

A "command palette" is also in the works: https://github.com/Metaxal/quickscript/issues/30#issuecomment-665640455

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser

**Comment by Metaxal** [comment]
If you want to investigate the keybindings issue, Quickscript can help!

This defines a custom keybinding that is applied only to the current buffer:
```racket
(define-script add-keybinding
  #:label "Add keybinding"
  #:output-to #f
  (λ (selection #:editor ed)
    (define kmap (send ed get-keymap))
    ; this adds a keybinding for the current editor only
    (send kmap add-function "mycustomkeybinding" (λ (ed ev) (send ed insert "CUSTOOOOOM")))
    (send kmap map-function "c:f8" "mycustomkeybinding")))
```
So if you open a new tab, then click on the quickscript, pressing ctl-f8 inserts a string, but the keybinding is mapped only in the current tab.

**Comment by sorawee** [comment]
Note: I added a new version of fishy completion. The previous version is reliable in a sense that it uses the result from check-syntax, meaning it can't be wrong. The new version is me doing my own thing, so I'm not sure if it's actually correct. That being said, the new version should be more efficient and has fewer limitations. When packaging the script, feel free to pick either one (or both).

**Comment by Metaxal** [comment]
Nice! Really it's up to you which one you want to include. I would avoid including both because people will get confused. Maybe script 2, as it seems more general?

(I think for this kind of script it's better to have something too tolerant than too strict, as the latter may just be regarded as "it doesn't work".)

**Comment by sorawee** [comment]
Script 2, then :)
