### ISSUE TITLE
Robo-Head-Pat

### ISSUE THREAD

**Issue by ghost** [Quickscript-Competiton/July2020entries#2]
## Code
[Gist](https://gist.github.com/lambduli/292df213d6b34f6b21eaf4308d6c279d)

## Licence 
Apache 2/MIT

## Contact details 
Lambduli on the Racket Slack

**Comment by spdegabrielle** [comment]
Thank you for your entry @Lambduli !
```
;__________
;| _    _  |    ___________
;|(^)  (^) |   /           |
;|    o    |  /  Good job! |
;|  \___/  | /_____________|
;+---------+
```

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser

**Comment by ghost** [comment]
Hi, I would very much like to. I am ready to accept the team invite right after it arrives.

Edit: I just noticed the invite on the main page of this project - but it said it has expired. Could you please try and send my one again?

Thank you.

**Comment by spdegabrielle** [comment]
Hi @Lambduli I’ve resent the invite! Thank you for contributing. 
Have you considered a second entry ? (Prizes!)

**Comment by ghost** [comment]
Hi @spdegabrielle, thank you very much - I successfully accepted the invite.
I have - but I haven't got any good inspiration yet. Hopefully it will change soon.
Though, for single entry there are stickers? Right? Or do I have to do two, if I want to share my appreciation for the Racket with the rest of the world?

**Comment by spdegabrielle** [comment]
> An exclusive badge for your github profile recognising your efforts and contribution to the community. (you must enable it )
> If you participate once, you get stickers,
> if you participate twice time, you get also a mug,
> if you participate three times, you get also a t-shirt
> (while stocks last. Note - prizes still available) You can participate more than once.

-> https://github.com/Quickscript-Competiton/July2020entries

**Comment by ghost** [comment]
Maybe I will try to get a mug too :). Thank you.

**Comment by spdegabrielle** [comment]
@Lambduli 

Don't be afraid to adapt or remix scripts to fit your needs. 

e.g. instead of starting from scratch; maybe remix the [different ways of speaking text on linux, macOS and windows](https://github.com/racket/racket/wiki/voice) with the [operating system detection in `open terminal here`](https://github.com/Metaxal/quickscript-extra/blob/master/scripts/open-terminal.rkt) to make a script that speaks the selected text.

For more ideas check out the resources below.

- [competition IDEAS.md](https://github.com/Quickscript-Competiton/July2020entries/blob/master/IDEAS.md)

- [quickscripts-extra collection](https://github.com/Metaxal/quickscript-extra/tree/master/scripts) 

- [other competition entries](https://github.com/Quickscript-Competiton/July2020entries/issues)

**Comment by ghost** [comment]
@spdegabrielle That's a great idea. I will give it a try.
