### ISSUE TITLE
line-count : count lines in selection / definitions

### ISSUE THREAD

**Issue by bennn** [Quickscript-Competiton/July2020entries#20]
I made a tiny script to count lines in a file.

At first, I wanted to use the `syntax-sloc` package. But I didn't see how to get a syntax object from DrRacket and I didn't want to depend on the `#:file` arg.

Then I realized it's great that the script doesn't need a well-formed syntax object to run. So the submission is very simple but works for all kinds of files.

## code
https://gist.github.com/bennn/52713a3c002eba9928f3b7ec256f1dc7

## Licence 
Apache 2/MIT

## contact details 
`@ben` on the racket slack

**Comment by Metaxal** [comment]
Great! Indeed it's probably better to rely on #:definitions rather than on #:file.

I don't think there's a direct way to retrieve the syntax object from DrRacket, but one possibility is to get the text, then read-syntax it, then navigate the syntax object to the selection's start and end positions with (send ed get-start-position). (I've done something like that for the extract-function script in quickscript-extra.)

**Comment by spdegabrielle** [comment]
In recognition of your efforts and contribution to the community you have been awarded the exclusive quickscripts competition badge for your GitHub profile!

It is not mandatory; for it to display you must first accept the team invite and you must [enable it](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership)
 
Please contact me if you have any questions or concerns.

Kind regards, 

Stephen De Gabrielle 
Competition Organiser
