### ISSUE TITLE
Script to plot numbers

### ISSUE THREAD

**Issue by hasn0life** [Quickscript-Competiton/July2020entries#21]
This code takes a selection of numbers which are separated by something sensible and plots them
The plot appears in a new tab in dr.racket

## code
https://gist.github.com/hasn0life/f58aab2750f9ebc767b79410b8abfca4

## Licence 
 Apache 2/MIT

## contact details 
https://github.com/hasn0life

**Comment by Metaxal** [comment]
Very nice!

One suggestion, if I may:
Instead of opening a new tab, you could open a new frame, using `plot-frame` instead of `plot-snip`. Note that plot-frame doesn't show the frame, so you need to write:
```racket
(define fr (plot-frame (lines plot-lst) #:x-label "" #:y-label "" ))
(send fr show #t)
```
which also needs a `(require racket/class)` at the top.

If you prefer, you can also write two `define-script` in the same file, one that opens in a new tab, one that opens in a frame for example.

**Comment by hasn0life** [comment]
Thank you for that! That was what I originally wanted but then I spent way too long trying to stuff the graph into a message box cause I didn't realize that you could open the frame without returning anything from the script (the other change is to set the #:output-to to #f). Its also really annoying to debug problems with the scripts when you run them from the script menu cause they tend to crash Dr. Racket for me. If there are some tricks for that please lmk

Also I'm trying to think of an interface for plotting multiple data sets. If you have any ideas on how that might look I'd be interested (perhaps persistent script and overlaying the data?).

**Comment by Metaxal** [comment]
*Crashing:*
It would be really helpful if you could reproduce one case where DrRacket crashes when writing a quickscript, and open an issue [here](https://github.com/Metaxal/quickscript/issues) so I can try to at least prevent the crash and report an error instead (if possible).

*Debugging:*
You can also run the script file just like a normal file, and call the script function like a normal function. (It's more complicated if you require arguments like `#:definitions` though.) For example if you script is something like
```racket
(define-script plot-numbers
  #:label "Plot"
  #:output-to #f
  (λ (selection)
    (make-plot selection)))
```
(btw, you should not name your script function `(define-script plot ...)` because it's the same name as the `plot` function that you are importing and using.)
You can run the module with DrRacket "Run" button, like a normal module, and in the interactions do:
```racket
> (plot-numbers "1 2 3")
<a-plot>
```

*Multiple data:*
A persistent script is a good idea (remember to click "Unload persistent scripts" if you want to test your script from scratch").
I think you'd need several menu items (so a submenu using `#:menu-path ("Plot selection")` would be useful):
* add selected data to plot,
* remove last data,
* reset.

You will need each script function to be `#:persistent` so that they access common global variables in your module.

Happy to help if you're stuck.

**Comment by Metaxal** [comment]
Oh, one really small thing: You can write all your requires into a single one like so:
```racket
(require quickscript
         plot
         racket/string
         racket/list
         racket/class)
```
It doesn't really change anything, it's just a little more compact and tidy :)

**Comment by hasn0life** [comment]
Hey, sorry it took me a minute but I updated the script to do multiple persistent lines in a single plot using your advice. Thanks for that!

**Comment by Metaxal** [comment]
Thanks! I've updated your script with your changes, but I couldn't resist doing a little more :smile: 

The problem was that each time you add data, it opens a new frame. So I [changed it](https://github.com/Quickscript-Competiton/July2020entries/blob/master/scripts/plot-selected-numbers.rkt) a little to have 2 buttons: "plot (new frame)" and "plot (reuse frame)".

Let me know what you think and if you prefer the way you did it, I'm happy to revert!

**Comment by hasn0life** [comment]
Yea good catch! I think that works even better.
